<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Arkn.Extensions.Repository.EntityFrameworkCore</RootNamespace>
    <AssemblyName>Arkn.Extensions.Repository.EntityFrameworkCore</AssemblyName>
    <Version>0.1.0</Version>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <Authors>Fernando Terra</Authors>
    <Description>EntityFrameworkCore implementation for Arkn.Repository.</Description>
    <PackageTags>dotnet;csharp;architecture;ddd;repository;efcore;entityframework</PackageTags>
    <RepositoryUrl>https://github.com/fernando-terra/arkn</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Arkn.Repository\Arkn.Repository.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
  </ItemGroup>
</Project>
