using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Arkn.SourceGen;

[Generator]
public sealed class ArknErrorsGenerator : IIncrementalGenerator
{
    // Attribute source injected into every consumer project
    private const string ArknErrorsAttributeSource = """
        // <auto-generated by Arkn.SourceGen />
        #nullable enable
        namespace Arkn.SourceGen
        {
            [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
            internal sealed class ArknErrorsAttribute : System.Attribute { }

            [System.AttributeUsage(System.AttributeTargets.Method, Inherited = false)]
            internal sealed class ArknErrorCodeAttribute : System.Attribute
            {
                public string ErrorType { get; }
                public string DefaultMessage { get; }
                public ArknErrorCodeAttribute(string errorType, string defaultMessage)
                {
                    ErrorType = errorType;
                    DefaultMessage = defaultMessage;
                }
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Always inject the attribute definitions
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource(
                "ArknSourceGenAttributes.g.cs",
                SourceText.From(ArknErrorsAttributeSource, Encoding.UTF8));
        });

        // 2. Find classes marked with [ArknErrors]
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsArknErrorsClass(node),
                transform:  static (ctx,  _) => GetClassInfo(ctx))
            .Where(static info => info is not null);

        // 3. Generate code for each class
        context.RegisterSourceOutput(classDeclarations, static (ctx, classInfo) =>
        {
            if (classInfo is null) return;
            var (source, hintName) = GenerateSource(classInfo);
            ctx.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
        });
    }

    private static bool IsArknErrorsClass(SyntaxNode node)
    {
        if (node is not ClassDeclarationSyntax cls) return false;
        return cls.AttributeLists
            .SelectMany(al => al.Attributes)
            .Any(a => a.Name.ToString() is "ArknErrors" or "ArknErrorsAttribute"
                                        or "Arkn.SourceGen.ArknErrors"
                                        or "Arkn.SourceGen.ArknErrorsAttribute");
    }

    private static ClassInfo? GetClassInfo(GeneratorSyntaxContext ctx)
    {
        var cls = (ClassDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(cls) as INamedTypeSymbol;
        if (symbol is null) return null;

        var methods = new List<ErrorMethodInfo>();

        foreach (var member in cls.Members.OfType<MethodDeclarationSyntax>())
        {
            // Must be partial
            if (!member.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword))) continue;

            // Must have [ArknErrorCode] attribute
            var attrSyntax = member.AttributeLists
                .SelectMany(al => al.Attributes)
                .FirstOrDefault(a => a.Name.ToString() is "ArknErrorCode" or "ArknErrorCodeAttribute"
                                                       or "Arkn.SourceGen.ArknErrorCode"
                                                       or "Arkn.SourceGen.ArknErrorCodeAttribute");

            if (attrSyntax?.ArgumentList?.Arguments.Count < 2) continue;

            var args       = attrSyntax!.ArgumentList!.Arguments;
            var errorType  = args[0].Expression.ToString().Trim('"');
            var defaultMsg = args[1].Expression.ToString().Trim('"');
            var methodName = member.Identifier.Text;

            methods.Add(new ErrorMethodInfo(methodName, errorType, defaultMsg));
        }

        return new ClassInfo(
            symbol.Name,
            symbol.ContainingNamespace?.IsGlobalNamespace == true
                ? null
                : symbol.ContainingNamespace?.ToDisplayString(),
            methods,
            cls.Modifiers.ToString());
    }

    private static (string source, string hintName) GenerateSource(ClassInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Arkn.SourceGen />");
        sb.AppendLine("// Do not edit manually — changes will be overwritten on rebuild.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (info.Namespace is not null)
        {
            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    {info.Modifiers} partial class {info.ClassName}");
        sb.AppendLine("    {");

        foreach (var method in info.Methods)
        {
            // Derive the error code: ClassName.MethodName
            var errorCode = $"{info.ClassName}.{method.MethodName}";

            // Map ErrorType string to Error factory method
            var factory = method.ErrorType switch
            {
                "NotFound"     or "ErrorType.NotFound"     => "NotFound",
                "Validation"   or "ErrorType.Validation"   => "Validation",
                "Conflict"     or "ErrorType.Conflict"     => "Conflict",
                "Unauthorized" or "ErrorType.Unauthorized" => "Unauthorized",
                "Forbidden"    or "ErrorType.Forbidden"    => "Forbidden",
                _                                          => "Failure",
            };

            sb.AppendLine($"        public static partial global::Arkn.Results.Error {method.MethodName}(string? detail = null) =>");
            sb.AppendLine($"            global::Arkn.Results.Error.{factory}(");
            sb.AppendLine($"                \"{errorCode}\",");
            sb.AppendLine($"                detail ?? \"{EscapeString(method.DefaultMessage)}\");");
            sb.AppendLine();
        }

        sb.AppendLine("    }");

        if (info.Namespace is not null)
            sb.AppendLine("}");

        var hintName = info.Namespace is not null
            ? $"{info.Namespace}.{info.ClassName}.g.cs"
            : $"{info.ClassName}.g.cs";

        return (sb.ToString(), hintName);
    }

    private static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    // ── Data models ───────────────────────────────────────────────────────────

    private sealed class ClassInfo
    {
        public string ClassName { get; }
        public string? Namespace { get; }
        public List<ErrorMethodInfo> Methods { get; }
        public string Modifiers { get; }

        public ClassInfo(string className, string? @namespace, List<ErrorMethodInfo> methods, string modifiers)
        {
            ClassName = className;
            Namespace = @namespace;
            Methods   = methods;
            Modifiers = modifiers;
        }
    }

    private sealed class ErrorMethodInfo
    {
        public string MethodName { get; }
        public string ErrorType { get; }
        public string DefaultMessage { get; }

        public ErrorMethodInfo(string methodName, string errorType, string defaultMessage)
        {
            MethodName    = methodName;
            ErrorType     = errorType;
            DefaultMessage = defaultMessage;
        }
    }
}
