using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Arkn.SourceGen;

[Generator]
public sealed class ArknRelayGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Find all classes that implement IRequestHandler<TRequest, TResponse>
        var requestHandlers = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsPotentialRequestHandler(node),
                transform: static (ctx, _) => GetRequestHandlerInfo(ctx))
            .Where(static info => info is not null);

        // 2. Generate the Source-Generated Relay Dispatcher
        context.RegisterSourceOutput(requestHandlers.Collect(), static (ctx, handlers) =>
        {
            if (handlers.IsDefaultOrEmpty) return;
            var source = GenerateRelayDispatcher(handlers);
            ctx.AddSource("ArknRelayDispatcher.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static bool IsPotentialRequestHandler(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax cls && cls.BaseList != null;
    }

    private static HandlerInfo? GetRequestHandlerInfo(GeneratorSyntaxContext ctx)
    {
        var cls = (ClassDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(cls) as INamedTypeSymbol;
        if (symbol == null || symbol.IsAbstract) return null;

        var handlerInterface = symbol.AllInterfaces.FirstOrDefault(i => 
            i.Name == "IRequestHandler" && i.TypeArguments.Length == 2);

        if (handlerInterface == null) return null;

        return new HandlerInfo(
            symbol.ToDisplayString(),
            handlerInterface.TypeArguments[0].ToDisplayString(),
            handlerInterface.TypeArguments[1].ToDisplayString());
    }

    private static string GenerateRelayDispatcher(System.Collections.Immutable.ImmutableArray<HandlerInfo?> handlers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Arkn.SourceGen />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Arkn.Relay.Abstractions;");
        sb.AppendLine("using Arkn.Core.Abstractions;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Arkn.Relay.Core;");
        sb.AppendLine();
        sb.AppendLine("public sealed class ArknGeneratedRelay : IRelay");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IServiceProvider _serviceProvider;");
        sb.AppendLine();
        sb.AppendLine("    public ArknGeneratedRelay(IServiceProvider serviceProvider) => _serviceProvider = serviceProvider;");
        sb.AppendLine();
        sb.AppendLine("    public async Task<TResponse> SendAsync<TResponse>(IRequest<TResponse> request, CancellationToken ct = default)");
        sb.AppendLine("        where TResponse : IResult");
        sb.AppendLine("    {");
        sb.AppendLine("        return request switch");
        sb.AppendLine("        {");

        foreach (var handler in handlers)
        {
            if (handler == null) continue;
            sb.AppendLine($"            {handler.RequestType} req => await DispatchAsync<{handler.RequestType}, {handler.ResponseType}>(req, ct),");
        }

        sb.AppendLine("            _ => throw new InvalidOperationException($\"No handler registered for {request.GetType().Name}\")");
        sb.AppendLine("        } is TResponse result ? result : throw new InvalidCastException();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private async Task<TResponse> DispatchAsync<TRequest, TResponse>(TRequest request, CancellationToken ct)");
        sb.AppendLine("        where TRequest : IRequest<TResponse>");
        sb.AppendLine("        where TResponse : IResult");
        sb.AppendLine("    {");
        sb.AppendLine("        var behaviors = _serviceProvider.GetServices<IPipelineBehavior<TRequest, TResponse>>().ToList();");
        sb.AppendLine("        var handler = _serviceProvider.GetRequiredService<IRequestHandler<TRequest, TResponse>>();");
        sb.AppendLine();
        sb.AppendLine("        RequestHandlerDelegate<TResponse> handlerDelegate = () => handler.HandleAsync(request, ct);");
        sb.AppendLine();
        sb.AppendLine("        if (behaviors.Count == 0) return await handlerDelegate();");
        sb.AppendLine();
        sb.AppendLine("        return await behaviors");
        sb.AppendLine("            .Reverse()");
        sb.AppendLine("            .Aggregate(handlerDelegate, (next, behavior) => () => behavior.HandleAsync(request, next, ct))();");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private sealed class HandlerInfo
    {
        public string HandlerType { get; }
        public string RequestType { get; }
        public string ResponseType { get; }

        public HandlerInfo(string handlerType, string requestType, string responseType)
        {
            HandlerType = handlerType;
            RequestType = requestType;
            ResponseType = responseType;
        }
    }
}
