using ModelContextProtocol.Server;
using System.ComponentModel;
using System.Text;
using System.Text.RegularExpressions;

namespace Arkn.MCP.Tools;

/// <summary>
/// refactor_to_result — converts exception-based C# code to the Arkn Result pattern,
/// including an auto-generated ErrorGroup class.
/// </summary>
[McpServerToolType]
public static class RefactorTools
{
    [McpServerTool, Description(
        "Converts C# code that uses exception-based error handling into the Arkn Result<T> pattern. " +
        "Generates an ErrorGroup class for the detected domain and returns the refactored method(s).")]
    public static string RefactorToResult(
        [Description("C# source code containing methods with exception-based error handling (throw, try/catch)")] string code,
        [Description("Domain name for the ErrorGroup class, e.g. 'Order', 'Payment'. Inferred from class name if empty.")] string domain = "")
    {
        if (string.IsNullOrWhiteSpace(code))
            return "Error: code cannot be empty.";

        // ── Infer domain from class name if not provided ──────────────────────
        var detectedDomain = domain;
        if (string.IsNullOrWhiteSpace(detectedDomain))
        {
            var classMatch = Regex.Match(code, @"class\s+(\w+)");
            detectedDomain = classMatch.Success
                ? Regex.Replace(classMatch.Groups[1].Value, "(Service|Repository|Handler|Controller)$", "")
                : "Domain";
        }
        detectedDomain = char.ToUpperInvariant(detectedDomain[0]) + detectedDomain[1..];

        // ── Collect thrown exception types ────────────────────────────────────
        var thrownExceptions = Regex
            .Matches(code, @"throw\s+new\s+(\w+(?:Exception)?)\s*\(([^)]*)\)")
            .Cast<Match>()
            .Select(m => (
                ExType: m.Groups[1].Value,
                Message: m.Groups[2].Value.Trim().Trim('"')
            ))
            .DistinctBy(t => t.ExType)
            .ToList();

        var errorMethods = new List<(string MethodName, string Code, string ErrorType)>();
        foreach (var (exType, message) in thrownExceptions)
        {
            var (methodName, arkErrorType) = ClassifyException(exType);
            var userMessage = string.IsNullOrWhiteSpace(message) ? $"{detectedDomain} operation failed." : message;
            errorMethods.Add((methodName, $"{detectedDomain}.{methodName}", arkErrorType));
        }

        // ── Build ErrorGroup class ────────────────────────────────────────────
        var egSb = new StringBuilder();
        egSb.AppendLine($"// ── {detectedDomain}Errors — generated by Arkn.MCP refactor_to_result ──");
        egSb.AppendLine("using Arkn.Results;");
        egSb.AppendLine("using Arkn.SourceGen;");
        egSb.AppendLine();
        egSb.AppendLine("[ArknErrors]");
        egSb.AppendLine($"public static partial class {detectedDomain}Errors");
        egSb.AppendLine("{");

        if (errorMethods.Count == 0)
        {
            egSb.AppendLine($"    [ArknErrorCode(\"NotFound\", \"{detectedDomain} was not found\")]");
            egSb.AppendLine($"    public static partial Error NotFound(string? detail = null);");
            egSb.AppendLine();
            egSb.AppendLine($"    [ArknErrorCode(\"Failure\", \"{detectedDomain} operation failed\")]");
            egSb.AppendLine($"    public static partial Error Failed(string? detail = null);");
        }
        else
        {
            foreach (var (methodName, _, errorType) in errorMethods)
            {
                egSb.AppendLine($"    [ArknErrorCode(\"{errorType}\", \"{detectedDomain} {methodName.ToLowerInvariant()} error\")]");
                egSb.AppendLine($"    public static partial Error {methodName}(string? detail = null);");
                egSb.AppendLine();
            }
        }
        egSb.AppendLine("}");

        // ── Refactor the method code ──────────────────────────────────────────
        var refactored = code;
        var changes = new List<string>();

        // 1. Add using
        if (!refactored.Contains("using Arkn.Results"))
        {
            refactored = "using Arkn.Results;\n" + refactored;
            changes.Add("Added 'using Arkn.Results;'");
        }

        // 2. void → Result, T → Result<T>
        refactored = Regex.Replace(refactored,
            @"\b(public|private|protected|internal)(\s+(?:async\s+)?)(void)(\s+\w+\s*\()",
            m => {
                changes.Add("Changed return type from void to Result");
                return $"{m.Groups[1].Value}{m.Groups[2].Value}Result{m.Groups[4].Value}";
            });

        // 3. throw new XException → return ErrorGroup method call
        refactored = Regex.Replace(refactored,
            @"throw\s+new\s+(\w+Exception)\s*\(([^)]*)\)\s*;",
            m => {
                var exType = m.Groups[1].Value;
                var (methodName, _) = ClassifyException(exType);
                changes.Add($"Replaced 'throw new {exType}' with {detectedDomain}Errors.{methodName}()");
                return $"return {detectedDomain}Errors.{methodName}({m.Groups[2].Value});";
            });

        // 4. throw; (rethrow) → return failure
        var hasRethrow = refactored.Contains("\nthrow;") || refactored.Contains(" throw;");
        if (hasRethrow)
        {
            refactored = Regex.Replace(refactored, @"\bthrow\s*;",
                $"return {detectedDomain}Errors.Failed(ex.Message);");
            changes.Add($"Replaced rethrow with {detectedDomain}Errors.Failed(ex.Message)");
        }

        // 5. async Task without Result → async Task<Result>
        if (changes.Any(c => c.Contains("Result")))
        {
            refactored = Regex.Replace(refactored, @"\basync\s+Task\b(?!\s*<)", "async Task<Result>");
        }

        // 6. Bare catch {} → catch with Result.Failure
        refactored = Regex.Replace(refactored,
            @"catch\s*\((\w+(?:\s+\w+)?)\)\s*\{\s*\}",
            m => {
                var exDecl = m.Groups[1].Value;
                var varName = exDecl.Contains(' ') ? exDecl.Split(' ')[1] : "ex";
                changes.Add("Added error return to empty catch block");
                return $"catch ({exDecl})\n{{\n    return {detectedDomain}Errors.Failed({varName}.Message);\n}}";
            });

        // ── Assemble output ───────────────────────────────────────────────────
        var sb = new StringBuilder();
        sb.AppendLine("// ════════════════════════════════════════════════════════════════════════");
        sb.AppendLine("// STEP 1 — ErrorGroup class (add to your domain project)");
        sb.AppendLine("// ════════════════════════════════════════════════════════════════════════");
        sb.AppendLine(egSb.ToString().TrimEnd());
        sb.AppendLine();
        sb.AppendLine("// ════════════════════════════════════════════════════════════════════════");
        sb.AppendLine("// STEP 2 — Refactored method(s)");
        sb.AppendLine("// ════════════════════════════════════════════════════════════════════════");
        sb.AppendLine(refactored.TrimEnd());
        sb.AppendLine();
        sb.AppendLine("// ── Changes applied ──────────────────────────────────────────────────────");
        if (changes.Count == 0)
            sb.AppendLine("// No automatic transformations applied — review code manually.");
        else
            foreach (var c in changes) sb.AppendLine($"// ✓ {c}");

        return sb.ToString();
    }

    /// <summary>Maps an exception type to an (ErrorGroupMethodName, ArknErrorType) pair.</summary>
    public static (string MethodName, string ErrorType) ClassifyException(string exceptionType)
    {
        var normalized = exceptionType.Replace("Exception", "");
        return normalized switch
        {
            "ArgumentNull" or "ArgumentOutOfRange" or "Argument" => ("Invalid", "Validation"),
            "InvalidOperation"                                    => ("InvalidOperation", "Conflict"),
            "NotFound" or "KeyNotFound"                          => ("NotFound", "NotFound"),
            "Unauthorized" or "UnauthorizedAccess"               => ("Unauthorized", "Unauthorized"),
            "Forbidden"                                           => ("Forbidden", "Forbidden"),
            "Timeout" or "TaskCanceled" or "OperationCanceled"   => ("TimedOut", "Failure"),
            "IO" or "File" or "Directory"                        => ("IoError", "Failure"),
            _                                                     => ("Failed", "Failure"),
        };
    }
}
