using ModelContextProtocol.Server;
using System.ComponentModel;

namespace Arkn.MCP.Tools;

[McpServerToolType]
public static class ScaffoldTools
{
    [McpServerTool, Description("Generates a complete Arkn error group class for a given domain name.")]
    public static string ScaffoldErrors(
        [Description("The domain name, e.g. 'User', 'Payment', 'Invoice'")] string domain)
    {
        if (string.IsNullOrWhiteSpace(domain))
            return "Error: domain name cannot be empty.";

        var d = char.ToUpperInvariant(domain[0]) + domain[1..];

        return $$"""
            using Arkn.Results;
            using Arkn.SourceGen;

            /// <summary>
            /// Error definitions for the {{d}} domain.
            /// Generated by Arkn.MCP scaffold_errors tool.
            /// </summary>
            [ArknErrors]
            public static partial class {{d}}Errors
            {
                [ArknErrorCode("NotFound", "{{d}} was not found")]
                public static partial Error NotFound(string? detail = null);

                [ArknErrorCode("Validation", "{{d}} data is invalid")]
                public static partial Error Invalid(string? detail = null);

                [ArknErrorCode("Conflict", "{{d}} already exists")]
                public static partial Error Conflict(string? detail = null);

                [ArknErrorCode("Unauthorized", "Access to {{d}} is not allowed")]
                public static partial Error Unauthorized(string? detail = null);
            }
            """;
    }

    [McpServerTool, Description("Generates an IArknJob implementation and DI registration snippet.")]
    public static string ScaffoldJob(
        [Description("Job class name, e.g. 'InvoiceProcessor'")] string name,
        [Description("Cron expression, e.g. '0 2 * * *'")] string cron,
        [Description("Optional description of what the job does")] string description = "")
    {
        if (string.IsNullOrWhiteSpace(name))
            return "Error: name cannot be empty.";
        if (string.IsNullOrWhiteSpace(cron))
            return "Error: cron expression cannot be empty.";

        var n = char.ToUpperInvariant(name[0]) + name[1..];
        var desc = string.IsNullOrWhiteSpace(description) ? $"Runs {n} job" : description;

        return $$"""
            using Arkn.Jobs.Abstractions;
            using Arkn.Jobs.Models;
            using Arkn.Logging.Abstractions;
            using Arkn.Results;

            /// <summary>{{desc}}</summary>
            public sealed class {{n}}Job(IArknLogger logger) : IArknJob
            {
                public async Task<Result> ExecuteAsync(ArknJobContext ctx)
                {
                    ctx.Log("Starting {{desc}}...");

                    // TODO: inject your services via constructor and implement logic here
                    await Task.Delay(0, ctx.CancellationToken);

                    ctx.Log("{{n}}Job completed successfully.");
                    return Result.Success();
                }
            }

            // ── DI Registration (Program.cs or Startup) ──────────────────────────────
            //
            // builder.Services.AddArknJobs(jobs =>
            // {
            //     jobs.Add<{{n}}Job>("{{cron}}")
            //         .WithName("{{n.ToLowerInvariant()}}-job")
            //         .WithDescription("{{desc}}")
            //         .WithRetry(maxAttempts: 3)
            //         .WithTimeout(TimeSpan.FromMinutes(5))
            //         .NotifyOn(JobEvent.Failed | JobEvent.TimedOut);
            // });
            """;
    }

    [McpServerTool, Description("Generates a typed Arkn HTTP client with methods inferred from operation names.")]
    public static string ScaffoldHttpClient(
        [Description("Client class name, e.g. 'PaymentGateway'")] string name,
        [Description("Base URL of the API, e.g. 'https://api.example.com'")] string baseUrl,
        [Description("Comma-separated list of operation names, e.g. 'GetUser,CreateUser,DeleteUser'")] string operations = "")
    {
        if (string.IsNullOrWhiteSpace(name))
            return "Error: name cannot be empty.";
        if (string.IsNullOrWhiteSpace(baseUrl))
            return "Error: baseUrl cannot be empty.";

        var n = char.ToUpperInvariant(name[0]) + name[1..];
        var ops = operations.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        var resource = n.ToLowerInvariant();

        var methods = ops.Length > 0
            ? string.Join("\n\n    ", ops.Select(op => GenerateMethod(op.Trim(), n, resource)))
            : $"    public Task<Result<{n}Response>> GetAsync(Guid id) =>\n        GetAs<{n}Response>(\"/{resource}/{{id}}\");";

        return $$"""
            using Arkn.Http;
            using Arkn.Results;

            /// <summary>
            /// Typed HTTP client for {{n}} API.
            /// Generated by Arkn.MCP scaffold_http_client tool.
            /// </summary>
            public sealed class {{n}}Client(IArknHttp http)
                : ArknHttpClient(http, "{{baseUrl}}")
            {
                {{methods}}
            }

            // ── DI Registration ───────────────────────────────────────────────────────
            //
            // builder.Services
            //     .AddArknHttp<{{n}}Client>("{{baseUrl}}")
            //     .WithRetry(maxAttempts: 3)
            //     .WithTimeout(TimeSpan.FromSeconds(30));
            """;
    }

    private static string GenerateMethod(string op, string name, string resource)
    {
        var lower = op.ToLowerInvariant();
        return lower switch
        {
            var s when s.StartsWith("get") && s.Contains("all") =>
                $"public Task<Result<IReadOnlyList<{name}Dto>>> GetAllAsync() =>\n        GetAs<IReadOnlyList<{name}Dto>>(\"/{resource}\");",
            var s when s.StartsWith("get") =>
                $"public Task<Result<{name}Dto>> GetAsync(Guid id) =>\n        GetAs<{name}Dto>(\"/{resource}/{{id}}\");",
            var s when s.StartsWith("create") || s.StartsWith("post") =>
                $"public Task<Result<{name}Dto>> CreateAsync({name}Request request) =>\n        PostAs<{name}Dto>(\"/{resource}\", request);",
            var s when s.StartsWith("update") || s.StartsWith("put") =>
                $"public Task<Result<{name}Dto>> UpdateAsync(Guid id, {name}Request request) =>\n        PutAs<{name}Dto>(\"/{resource}/{{id}}\", request);",
            var s when s.StartsWith("delete") =>
                $"public Task<Result> DeleteAsync(Guid id) =>\n        Delete(\"/{resource}/{{id}}\");",
            _ =>
                $"public Task<Result<{name}Dto>> {op}Async() =>\n        GetAs<{name}Dto>(\"/{resource}/{lower}\");"
        };
    }
}
