using ModelContextProtocol.Server;
using System.ComponentModel;
using System.Text;
using System.Text.RegularExpressions;

namespace Arkn.MCP.Tools;

/// <summary>
/// generate_tests — generates xUnit tests covering the success path and each
/// possible ErrorType for a method returning Result or Result&lt;T&gt;.
/// </summary>
[McpServerToolType]
public static class TestGenTools
{
    [McpServerTool, Description(
        "Generates xUnit unit tests for a C# method that returns Result or Result<T>. " +
        "Produces test cases for the success path and one test per error code found in the class or " +
        "inferred from the method signature. Tests follow the Arrange/Act/Assert pattern.")]
    public static string GenerateTests(
        [Description("Method signature or full method source code returning Result or Result<T>, e.g. 'public async Task<Result<UserDto>> GetUserAsync(Guid id)'")] string methodSignature,
        [Description("Class or service name under test, e.g. 'UserService'. Inferred from signature if empty.")] string className = "",
        [Description("Comma-separated error codes that the method can return, e.g. 'User.NotFound,User.InvalidEmail'. Inferred from method body if empty.")] string errorCodes = "")
    {
        if (string.IsNullOrWhiteSpace(methodSignature))
            return "Error: method signature cannot be empty.";

        // ── Parse method signature ────────────────────────────────────────────
        var sig        = methodSignature.Trim();
        var isAsync    = sig.Contains("async") || sig.Contains("Task");
        var awaitKw    = isAsync ? "await " : "";
        var asyncKw    = isAsync ? "async Task" : "void";

        // Extract method name
        var nameMatch  = Regex.Match(sig, @"\b(\w+)\s*\(");
        var methodName = nameMatch.Success ? nameMatch.Groups[1].Value : "Method";
        methodName     = Regex.Replace(methodName, @"^(public|private|protected|internal|async|static|override)\s*", "");

        // Extract return type (Result<T> or Result)
        var rtMatch   = Regex.Match(sig, @"Result<(\w+)>");
        var innerType = rtMatch.Success ? rtMatch.Groups[1].Value : "";
        var hasValue  = !string.IsNullOrWhiteSpace(innerType);

        // Extract parameters
        var paramMatch = Regex.Match(sig, @"\(([^)]*)\)");
        var paramStr   = paramMatch.Success ? paramMatch.Groups[1].Value.Trim() : "";
        var parameters = ParseParameters(paramStr);

        // Extract class/service name
        var svcName = string.IsNullOrWhiteSpace(className)
            ? InferClassName(sig, methodName)
            : className;
        var svcInterface = $"I{svcName}";
        var svcVar       = char.ToLowerInvariant(svcName[0]) + svcName[1..];

        // ── Collect error codes ───────────────────────────────────────────────
        var codes = new List<(string Code, string ErrorType)>();
        if (!string.IsNullOrWhiteSpace(errorCodes))
        {
            foreach (var raw in errorCodes.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                var dotIdx = raw.IndexOf('.');
                var reason = dotIdx >= 0 ? raw[(dotIdx + 1)..] : raw;
                var errType = InferErrorType(reason);
                codes.Add((raw, errType));
            }
        }
        else
        {
            // Infer error codes from method body if provided
            foreach (Match m in Regex.Matches(sig, @"Error\.(NotFound|Validation|Conflict|Unauthorized|Forbidden|Failure)\s*\(\s*""([^""]+)"""))
            {
                var code    = m.Groups[2].Value;
                var errType = m.Groups[1].Value;
                if (!codes.Any(c => c.Code == code)) codes.Add((code, errType));
            }

            // Fallback: generate 2 common error codes from method name
            if (codes.Count == 0)
            {
                var ns = InferDomain(methodName);
                codes.Add(($"{ns}.NotFound", "NotFound"));
                if (hasValue) codes.Add(($"{ns}.Invalid", "Validation"));
            }
        }

        // ── Build argument placeholders for the call ──────────────────────────
        var argList = string.Join(", ", parameters.Select(p => DefaultValue(p.Type, p.Name)));

        // ── Generate test class ───────────────────────────────────────────────
        var sb = new StringBuilder();
        sb.AppendLine("// ── Generated by Arkn.MCP generate_tests ─────────────────────────────────");
        sb.AppendLine("using Arkn.Results;");
        sb.AppendLine("using NSubstitute;");
        sb.AppendLine("using Xunit;");
        sb.AppendLine();
        sb.AppendLine($"namespace YourProject.Tests;");
        sb.AppendLine();
        sb.AppendLine($"public class {methodName}Tests");
        sb.AppendLine("{");

        // ── Setup helper ──────────────────────────────────────────────────────
        sb.AppendLine($"    private static {svcInterface} BuildSut() => Substitute.For<{svcInterface}>();");
        sb.AppendLine();

        // ── Success test ──────────────────────────────────────────────────────
        sb.AppendLine($"    // ── Success path ─────────────────────────────────────────────────────────");
        sb.AppendLine();
        sb.AppendLine($"    [Fact]");
        sb.AppendLine($"    public {asyncKw} {methodName}_ValidInput_ShouldReturnSuccess()");
        sb.AppendLine("    {");
        sb.AppendLine($"        // Arrange");
        sb.AppendLine($"        var sut = BuildSut();");
        if (parameters.Count > 0)
        {
            foreach (var p in parameters)
                sb.AppendLine($"        var {p.Name} = {DefaultValue(p.Type, p.Name)};");
        }
        if (hasValue)
        {
            sb.AppendLine($"        var expected = new {innerType}(/* TODO: fill */);");
            sb.AppendLine($"        sut.{methodName}({string.Join(", ", parameters.Select(p => p.Name))}){(isAsync ? ".Returns(Task.FromResult(Result.Success(expected)))" : ".Returns(Result.Success(expected))")};");
        }
        else
        {
            sb.AppendLine($"        sut.{methodName}({string.Join(", ", parameters.Select(p => p.Name))}){(isAsync ? ".Returns(Task.FromResult(Result.Success()))" : ".Returns(Result.Success())")};");
        }
        sb.AppendLine();
        sb.AppendLine($"        // Act");
        sb.AppendLine($"        var result = {awaitKw}sut.{methodName}({argList});");
        sb.AppendLine();
        sb.AppendLine($"        // Assert");
        sb.AppendLine($"        Assert.True(result.IsSuccess);");
        if (hasValue) sb.AppendLine($"        Assert.Equal(expected, result.Value);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ── Error tests ───────────────────────────────────────────────────────
        sb.AppendLine($"    // ── Failure paths ────────────────────────────────────────────────────────");
        sb.AppendLine();

        foreach (var (code, errorType) in codes)
        {
            var dotIdx   = code.IndexOf('.');
            var codePart = dotIdx >= 0 ? code[(dotIdx + 1)..] : code;
            var testName = $"{methodName}_{codePart}_ShouldReturnFailure";

            sb.AppendLine($"    [Fact]");
            sb.AppendLine($"    public {asyncKw} {testName}()");
            sb.AppendLine("    {");
            sb.AppendLine($"        // Arrange");
            sb.AppendLine($"        var sut     = BuildSut();");
            sb.AppendLine($"        var error   = Error.{errorType}(\"{code}\", \"TODO: expected message\");");
            if (hasValue)
                sb.AppendLine($"        sut.{methodName}({argList}){(isAsync ? ".Returns(Task.FromResult(Result.Failure<{innerType}>(error)))" : $".Returns(Result.Failure<{innerType}>(error))")};");
            else
                sb.AppendLine($"        sut.{methodName}({argList}){(isAsync ? ".Returns(Task.FromResult(Result.Failure(error)))" : ".Returns(Result.Failure(error))")};");
            sb.AppendLine();
            sb.AppendLine($"        // Act");
            sb.AppendLine($"        var result = {awaitKw}sut.{methodName}({argList});");
            sb.AppendLine();
            sb.AppendLine($"        // Assert");
            sb.AppendLine($"        Assert.True(result.IsFailure);");
            sb.AppendLine($"        Assert.Equal(ErrorType.{errorType}, result.FirstError.Type);");
            sb.AppendLine($"        Assert.Equal(\"{code}\", result.FirstError.Code);");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// ── Notes ────────────────────────────────────────────────────────────────────");
        sb.AppendLine("// • Replace NSubstitute with your preferred mocking library (Moq, FakeItEasy)");
        sb.AppendLine("// • Fill in 'TODO' placeholders with real values from your domain");
        sb.AppendLine($"// • {svcInterface} must be an interface — extract one if it doesn't exist yet");
        if (isAsync)
            sb.AppendLine("// • Add 'using System.Threading.Tasks;' if not in global usings");

        return sb.ToString();
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private sealed record ParameterInfo(string Type, string Name);

    private static List<ParameterInfo> ParseParameters(string paramStr)
    {
        if (string.IsNullOrWhiteSpace(paramStr)) return [];

        return paramStr
            .Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Select(p =>
            {
                var parts = p.Trim().Split(' ', StringSplitOptions.RemoveEmptyEntries);
                return parts.Length >= 2
                    ? new ParameterInfo(parts[^2], parts[^1])
                    : new ParameterInfo("object", parts[0]);
            })
            .ToList();
    }

    private static string DefaultValue(string type, string name) => type.ToLowerInvariant() switch
    {
        "guid"    => $"Guid.NewGuid()",
        "string"  => $"\"test-{name}\"",
        "int"     => "1",
        "long"    => "1L",
        "decimal" => "1.00m",
        "bool"    => "true",
        "datetime" or "datetimeoffset" => "DateTimeOffset.UtcNow",
        _         => $"new {type}(/* TODO */)",
    };

    private static string InferClassName(string sig, string methodName)
    {
        // Try to find the class name before the method
        var match = Regex.Match(sig, @"(\w+)\s*\.", RegexOptions.RightToLeft);
        if (match.Success) return match.Groups[1].Value;
        return InferDomain(methodName) + "Service";
    }

    private static string InferDomain(string methodName)
    {
        // Strip verb prefix (Get, Create, Update, Delete, Process, etc.)
        var stripped = Regex.Replace(methodName, @"^(Get|Create|Update|Delete|Process|Handle|Execute|Find|Fetch|Add|Remove|Cancel|Activate|Deactivate)(All|By\w+)?", "");
        return string.IsNullOrWhiteSpace(stripped) ? "Domain" : stripped.TrimEnd('s', 'A', 'a'); // naive depluralize
    }

    private static string InferErrorType(string reason) => reason.ToLowerInvariant() switch
    {
        "notfound" or "missing"              => "NotFound",
        "invalid" or "validation" or "bad"  => "Validation",
        "conflict" or "duplicate" or "exists" => "Conflict",
        "unauthorized" or "unauthenticated" => "Unauthorized",
        "forbidden" or "accessdenied"       => "Forbidden",
        _                                   => "Failure",
    };
}
