<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Arkn.Extensions.Repository.PostgreSql</RootNamespace>
    <AssemblyName>Arkn.Extensions.Repository.PostgreSql</AssemblyName>
    <Version>0.1.0-alpha</Version>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <Authors>Fernando Terra</Authors>
    <Description>PostgreSql extension for Arkn Repository (EntityFrameworkCore).</Description>
    <PackageTags>dotnet;csharp;architecture;ddd;repository;efcore;postgresql;npgsql</PackageTags>
    <RepositoryUrl>https://github.com/fernando-terra/arkn</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Arkn.Extensions.Repository.EntityFrameworkCore\Arkn.Extensions.Repository.EntityFrameworkCore.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0" />
  </ItemGroup>
</Project>
